// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Adopt(arg1) {
  return window['go']['main']['Bridge']['Adopt'](arg1);
}

export function DeleteBoard(arg1) {
  return window['go']['main']['Bridge']['DeleteBoard'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['Bridge']['DeleteNote'](arg1);
}

export function DeskMove(arg1, arg2, arg3) {
  return window['go']['main']['Bridge']['DeskMove'](arg1, arg2, arg3);
}

export function File(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Bridge']['File'](arg1, arg2, arg3, arg4);
}

export function Model() {
  return window['go']['main']['Bridge']['Model']();
}

export function NewBoard(arg1) {
  return window['go']['main']['Bridge']['NewBoard'](arg1);
}

export function NewNote(arg1, arg2, arg3) {
  return window['go']['main']['Bridge']['NewNote'](arg1, arg2, arg3);
}

export function Note(arg1) {
  return window['go']['main']['Bridge']['Note'](arg1);
}

export function Pin(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Bridge']['Pin'](arg1, arg2, arg3, arg4);
}

export function RegisterAdd(arg1, arg2, arg3) {
  return window['go']['main']['Bridge']['RegisterAdd'](arg1, arg2, arg3);
}

export function RegisterRemove(arg1, arg2) {
  return window['go']['main']['Bridge']['RegisterRemove'](arg1, arg2);
}

export function RenameBoard(arg1, arg2) {
  return window['go']['main']['Bridge']['RenameBoard'](arg1, arg2);
}

export function Search(arg1) {
  return window['go']['main']['Bridge']['Search'](arg1);
}

export function SetPrefs(arg1) {
  return window['go']['main']['Bridge']['SetPrefs'](arg1);
}

export function SetSettings(arg1) {
  return window['go']['main']['Bridge']['SetSettings'](arg1);
}

export function SwitchVault() {
  return window['go']['main']['Bridge']['SwitchVault']();
}

export function Unpin(arg1, arg2) {
  return window['go']['main']['Bridge']['Unpin'](arg1, arg2);
}

export function UpdateNote(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['Bridge']['UpdateNote'](arg1, arg2, arg3, arg4, arg5);
}

export function VaultPath() {
  return window['go']['main']['Bridge']['VaultPath']();
}
