// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {slipbox} from '../models';

export function Adopt(arg1:string):Promise<model.Detail>;

export function DeleteBoard(arg1:string):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeskMove(arg1:string,arg2:number,arg3:number):Promise<void>;

export function File(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.Detail>;

export function Model():Promise<model.Vault>;

export function NewBoard(arg1:string):Promise<slipbox.Board>;

export function NewNote(arg1:string,arg2:string,arg3:string):Promise<model.Detail>;

export function Note(arg1:string):Promise<model.Detail>;

export function Pin(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function RegisterAdd(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RegisterRemove(arg1:string,arg2:string):Promise<void>;

export function RenameBoard(arg1:string,arg2:string):Promise<void>;

export function Search(arg1:string):Promise<Array<model.Note>>;

export function SetPrefs(arg1:Record<string, any>):Promise<void>;

export function SetSettings(arg1:slipbox.Settings):Promise<void>;

export function SwitchVault():Promise<void>;

export function Unpin(arg1:string,arg2:string):Promise<void>;

export function UpdateNote(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<model.Detail>;

export function VaultPath():Promise<string>;
